// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qala.Game.Matches.EntityFrameworkCore;

#nullable disable

namespace Qala.Game.Matches.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(MatchesDbContext))]
    partial class MatchesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("matches")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qala.Game.Matches.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChallengeCode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorDisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("CreatorRating")
                        .HasColumnType("float");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EndReason")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FlagFallsAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("IncrementMs")
                        .HasColumnType("bigint");

                    b.Property<long>("InitialMs")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("NorthClockMs")
                        .HasColumnType("bigint");

                    b.Property<string>("NorthDisplayName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("NorthPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("NorthRating")
                        .HasColumnType("float");

                    b.Property<int>("Ply")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(96)
                        .IsUnicode(false)
                        .HasColumnType("varchar(96)");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("SouthClockMs")
                        .HasColumnType("bigint");

                    b.Property<string>("SouthDisplayName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("SouthPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SouthRating")
                        .HasColumnType("float");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TurnStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Winner")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeCode")
                        .IsUnique()
                        .HasFilter("[ChallengeCode] IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NorthPlayerId");

                    b.HasIndex("SouthPlayerId");

                    b.HasIndex("Status", "FlagFallsAt");

                    b.HasIndex("Status", "FinishedAt", "RulesVersion");

                    b.ToTable("Matches", "matches");
                });

            modelBuilder.Entity("Qala.Game.Matches.Domain.Entities.MatchMove", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ClockAfterMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notation")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ply")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Ply")
                        .IsUnique();

                    b.ToTable("MatchMoves", "matches");
                });

            modelBuilder.Entity("Qala.Game.Matches.Domain.Entities.PlayerRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<double>("RatingDeviation")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlayerRatings", "matches");
                });

            modelBuilder.Entity("Qala.Game.Matches.Domain.Entities.MatchMove", b =>
                {
                    b.HasOne("Qala.Game.Matches.Domain.Entities.Match", null)
                        .WithMany("Moves")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qala.Game.Matches.Domain.Entities.Match", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
