include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/l10n/generated/**
    - "**/*.g.dart"
    - build/**
    - android/**
    - ios/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Public API docs are not required in an app package.
    public_member_api_docs: false
